# General Configuration
version: '1.0.2.{build}'
skip_branch_with_pr: true


# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  # init and update submodules
  - git submodule update --recursive --init
  # update node.js to latest 10.x release
  - ps: Install-Product node 10
  - node --version
  - npm --version

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'

# Build Configuration
platform: Any CPU
configuration: Release

before_build:
  - nuget restore SpeckleRevit.sln
  - mkdir Release
  # install npm dependencies for SpeckleUi and build
  - cd SpeckleUi\App
  - npm install
  - npm run build
  # return to build dir
  - cd ..\..
  # maybe needed for local build events to go through 
  - mkdir %localappdata%\Autodesk\REVIT\Addins\2019

build:
  project: SpeckleRevit.sln
  verbosity: minimal

after_build:
  # zip everything up into a .rhi package
  # - 7z a -tzip -r specklerhino.rhi "%APPVEYOR_BUILD_FOLDER%\SpeckleRhinoPlugin\SpeckleWinR6\bin\Release\*"
  # - 7z a -tzip -r specklerhino.rhi "%APPVEYOR_BUILD_FOLDER%\SpeckleGrasshopper\bin\Release\*"
  - 7z a SpeckleRevit-%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\Release\*"
 
artifacts:
  path: SpeckleRevit-%APPVEYOR_BUILD_VERSION%.zip
  name: Release

deploy:
  - release: SpeckleRevit-$(APPVEYOR_BUILD_VERSION)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Speckle client for Revit.'
    provider: GitHub
    auth_token:
      secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe # your encrypted token from GitHub
    artifact: SpeckleRevit-$(APPVEYOR_BUILD_VERSION).zip
    draft: false
    prerelease: true
    force_update: true
    on:              # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only